# Module 5 - Chapter 7 Practice from Reading and Self Checks

In [1]:
import numpy as np

In [2]:
numbers = np.array([2, 3, 7, 11])

In [3]:
type(numbers)

numpy.ndarray

In [4]:
numbers

array([ 2,  3,  7, 11])

In [5]:
np.array([[1, 2, 3], [4, 5, 6]])

array([[1, 2, 3],
       [4, 5, 6]])

#### Self Check 7.2

In [6]:
import numpy as np

In [7]:
np.array([x for x in range(2, 21, 2)])

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [8]:
np.array([[2, 4, 6, 8, 10],[1, 3, 5, 7, 9]])

array([[ 2,  4,  6,  8, 10],
       [ 1,  3,  5,  7,  9]])

#### Chapter 7.3 - Array Attributes

In [9]:
import numpy as np

In [10]:
integers = np.array([[1, 2, 3], [4, 5, 6]])

In [11]:
integers

array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
floats = np.array([0.0, 0.1, 0.2, 0.3, 0.4])

In [13]:
floats

array([0. , 0.1, 0.2, 0.3, 0.4])

In [14]:
integers.dtype

dtype('int32')

In [15]:
floats.dtype

dtype('float64')

In [16]:
integers.ndim

2

In [17]:
floats.ndim

1

In [18]:
integers.shape

(2, 3)

In [19]:
floats.shape

(5,)

In [20]:
integers.size

6

In [21]:
integers.itemsize

4

In [22]:
floats.size

5

In [23]:
floats.itemsize

8

In [24]:
for row in integers:
    for column in row:
        print(column, end=' ')
    print()

1 2 3 
4 5 6 


In [25]:
for i in integers.flat:
    print(i, end=' ')

1 2 3 4 5 6 

#### Self Check 7.3

In [26]:
import numpy as np

In [27]:
a = np.array([[2, 4, 6, 8, 10], [1, 3, 5, 7, 9]])

In [28]:
a.ndim

2

In [29]:
a.shape

(2, 5)

In [30]:
a.size

10

#### Chapter 7.4 Filling Arrays with Specific Values

In [31]:
import numpy as np

In [32]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [33]:
np.ones((2, 4), dtype = int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

In [36]:
np.full((3, 5), 13)

array([[13, 13, 13, 13, 13],
       [13, 13, 13, 13, 13],
       [13, 13, 13, 13, 13]])

#### Chapter 7.5 Creating Arrays from Ranges

In [37]:
import numpy as np

In [39]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [40]:
np.arange(5,10)

array([5, 6, 7, 8, 9])

In [41]:
np.arange(10, 1, -2)

array([10,  8,  6,  4,  2])

In [42]:
np.linspace(0.0, 1.0, num=5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [43]:
np.arange(1, 21).reshape(4, 5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [44]:
np.arange(1, 100001).reshape(4, 25000)

array([[     1,      2,      3, ...,  24998,  24999,  25000],
       [ 25001,  25002,  25003, ...,  49998,  49999,  50000],
       [ 50001,  50002,  50003, ...,  74998,  74999,  75000],
       [ 75001,  75002,  75003, ...,  99998,  99999, 100000]])

#### Self Check 7.5

In [45]:
import numpy as np

In [46]:
np.arange(2, 41, 2).reshape(4, 5)

array([[ 2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20],
       [22, 24, 26, 28, 30],
       [32, 34, 36, 38, 40]])

#### Chapter 7.6 - List vs. Array Performance

In [47]:
import random

In [48]:
%timeit rolls_list = \
        [random.randrange(1, 7) for i in range(0, 6_000_000)]

4.23 s ± 19.5 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [49]:
import numpy as np

In [50]:
%timeit rolls_array = np.random.randint(1, 7, 6_000_000)

53 ms ± 735 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [51]:
%timeit rolls_array = np.random.randint(1, 7, 600_000_000)

5.78 s ± 463 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [52]:
%timeit ross_array = np.random.randint(1, 7, 60_000_000)

533 ms ± 16.2 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [53]:
%timeit -n3 -r2 rolls_array = np.random.randint(1, 7, 6_000_000)

54 ms ± 114 µs per loop (mean ± std. dev. of 2 runs, 3 loops each)


#### Self Check 7.6

In [54]:
import numpy as np

In [55]:
%timeit sum([x for x in range(10_000_000)])

750 ms ± 12.1 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [56]:
%timeit np.arange(10_000_000).sum()

16.6 ms ± 390 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


#### Chapter 7.7 arra Operators

In [57]:
import numpy as np

In [59]:
numbers = np.arange(1, 6)

In [60]:
numbers

array([1, 2, 3, 4, 5])

In [61]:
numbers * 2

array([ 2,  4,  6,  8, 10])

In [62]:
numbers ** 3

array([  1,   8,  27,  64, 125], dtype=int32)

In [63]:
numbers # this shows that the original array of numbers is unchanged by the calculations

array([1, 2, 3, 4, 5])

In [64]:
numbers += 10

In [65]:
numbers

array([11, 12, 13, 14, 15])

In [67]:
numbers2 = np.linspace(1.1, 5.5, 5)

In [68]:
numbers2

array([1.1, 2.2, 3.3, 4.4, 5.5])

In [69]:
numbers * numbers2

array([12.1, 26.4, 42.9, 61.6, 82.5])

In [70]:
numbers

array([11, 12, 13, 14, 15])

In [71]:
numbers >= 13

array([False, False,  True,  True,  True])

In [72]:
numbers2

array([1.1, 2.2, 3.3, 4.4, 5.5])

In [74]:
numbers2 < numbers

array([ True,  True,  True,  True,  True])

In [75]:
numbers == numbers2

array([False, False, False, False, False])

In [76]:
numbers == numbers

array([ True,  True,  True,  True,  True])

#### Self Check 7.7

In [77]:
import numpy as np

In [78]:
np.arange(1, 6) ** 2

array([ 1,  4,  9, 16, 25])

#### Chapter 7.8 - NumPy Calculation Methods

In [79]:
import numpy as np

In [80]:
grades = np.array([[87, 96, 70], [100, 87, 90], [94, 77, 90], [100, 81, 82]])

In [81]:
grades

array([[ 87,  96,  70],
       [100,  87,  90],
       [ 94,  77,  90],
       [100,  81,  82]])

In [82]:
grades.sum()

1054

In [83]:
grades.min()

70

In [84]:
grades.max()

100

In [85]:
grades.mean()

87.83333333333333

In [86]:
grades.std()

8.792357792739987

In [87]:
grades.var()

77.30555555555556

In [88]:
grades.mean(axis=0)

array([95.25, 85.25, 83.  ])

In [89]:
grades.mean(axis=1)

array([84.33333333, 92.33333333, 87.        , 87.66666667])

#### Self Check 7.8

In [90]:
import numpy as np

In [92]:
grades = np.random.randint(60, 101, 12).reshape(3, 4)

In [93]:
grades

array([[ 69,  86, 100,  76],
       [ 68,  76,  96,  68],
       [ 76,  70,  74,  87]])

In [94]:
grades.mean()

78.83333333333333

In [95]:
grades.mean(axis=0)

array([71.        , 77.33333333, 90.        , 77.        ])

In [96]:
grades.mean(axis=1)

array([82.75, 77.  , 76.75])

#### Chapter 7.9 - Universal Functions

In [97]:
import numpy as np

In [98]:
numbers = np.array([1, 4, 9, 16, 25, 36])

In [99]:
np.sqrt(numbers)

array([1., 2., 3., 4., 5., 6.])

In [100]:
numbers2 = np.arange(1, 7) * 10

In [101]:
numbers2

array([10, 20, 30, 40, 50, 60])

In [102]:
np.add(numbers, numbers2)

array([11, 24, 39, 56, 75, 96])

In [103]:
np.multiply(numbers2, 5)

array([ 50, 100, 150, 200, 250, 300])

In [104]:
number3 = numbers2.reshape(2, 3)

In [106]:
number3

array([[10, 20, 30],
       [40, 50, 60]])

In [107]:
numbers4 = np.array([2, 4, 6])

In [108]:
np.multiply(number3, numbers4)

array([[ 20,  80, 180],
       [ 80, 200, 360]])

#### Self Check 7.9

In [109]:
import numpy as np

In [110]:
numbers = np.arange(1, 6)

In [111]:
np.power(numbers, 3)

array([  1,   8,  27,  64, 125], dtype=int32)

#### Chapter 7.10 - Indexing and Slicing

In [112]:
import numpy as np

In [114]:
grades = np.array([[87, 96, 70], [100, 87, 90], [94, 77, 90], [100, 81, 82]])

In [115]:
grades

array([[ 87,  96,  70],
       [100,  87,  90],
       [ 94,  77,  90],
       [100,  81,  82]])

In [116]:
grades[0, 1]

96

In [117]:
grades[1]

array([100,  87,  90])

In [118]:
grades[0:2]

array([[ 87,  96,  70],
       [100,  87,  90]])

In [119]:
grades[[1, 3]]

array([[100,  87,  90],
       [100,  81,  82]])

In [120]:
grades[:, 0]

array([ 87, 100,  94, 100])

In [121]:
grades[:, 1:3]

array([[96, 70],
       [87, 90],
       [77, 90],
       [81, 82]])

In [122]:
grades[:, [0, 2]]

array([[ 87,  70],
       [100,  90],
       [ 94,  90],
       [100,  82]])

#### Self Check 7.10

In [123]:
import numpy as np

In [124]:
a = np.arange(1, 16).reshape(3, 5)

In [125]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [126]:
a[1]

array([ 6,  7,  8,  9, 10])

In [127]:
a[[0, 2]]

array([[ 1,  2,  3,  4,  5],
       [11, 12, 13, 14, 15]])

In [128]:
a[:, 1:4]

array([[ 2,  3,  4],
       [ 7,  8,  9],
       [12, 13, 14]])

#### Views: Shallow Copies

In [129]:
import numpy as np

In [130]:
numbers = np.arange(1, 6)

In [131]:
numbers

array([1, 2, 3, 4, 5])

In [132]:
numbers2 = numbers.view()

In [133]:
numbers2

array([1, 2, 3, 4, 5])

In [135]:
id(numbers)

3107577685744

In [136]:
id(numbers2)

3107577553520

In [137]:
numbers[1] *= 10

In [138]:
numbers2

array([ 1, 20,  3,  4,  5])

In [139]:
numbers

array([ 1, 20,  3,  4,  5])

In [140]:
numbers2[1] /= 10

In [141]:
numbers

array([1, 2, 3, 4, 5])

In [142]:
numbers2

array([1, 2, 3, 4, 5])

In [143]:
numbers2 = numbers[0:3]

In [144]:
numbers2

array([1, 2, 3])

In [145]:
id(numbers)

3107577685744

In [146]:
id(numbers2)

3107577430064

In [147]:
numbers2[3]

IndexError: index 3 is out of bounds for axis 0 with size 3

In [148]:
numbers[1] *= 20

In [150]:
numbers

array([ 1, 40,  3,  4,  5])

In [151]:
numbers2

array([ 1, 40,  3])

#### Chapter 7.12 - Deep Copies

In [152]:
import numpy as np

In [153]:
numbers = np.arange(1, 6)

In [154]:
numbers

array([1, 2, 3, 4, 5])

In [155]:
numbers2 = numbers.copy()

In [156]:
numbers2

array([1, 2, 3, 4, 5])

In [157]:
numbers[1] *= 10

In [158]:
numbers

array([ 1, 20,  3,  4,  5])

In [159]:
numbers2

array([1, 2, 3, 4, 5])

#### Chapter 7.13 - Reshaping and Transposing

In [160]:
import numpy as np

In [161]:
grades = np.array([[87, 96, 70], [100, 87, 90]])

In [162]:
grades

array([[ 87,  96,  70],
       [100,  87,  90]])

In [163]:
grades.reshape(1, 6)

array([[ 87,  96,  70, 100,  87,  90]])

In [164]:
grades

array([[ 87,  96,  70],
       [100,  87,  90]])

In [165]:
grades.resize(1, 6)

In [166]:
grades

array([[ 87,  96,  70, 100,  87,  90]])

In [167]:
grades = np.array([[87, 96, 70], [100, 87, 90]])

In [168]:
flattened = grades.flatten()

In [169]:
grades

array([[ 87,  96,  70],
       [100,  87,  90]])

In [170]:
flattened

array([ 87,  96,  70, 100,  87,  90])

In [171]:
flattened[0] = 100

In [172]:
flattened

array([100,  96,  70, 100,  87,  90])

In [173]:
grades

array([[ 87,  96,  70],
       [100,  87,  90]])

In [174]:
raveled = grades.ravel()

In [175]:
raveled

array([ 87,  96,  70, 100,  87,  90])

In [176]:
grades

array([[ 87,  96,  70],
       [100,  87,  90]])

In [177]:
raveled[0] = 100

In [178]:
raveled

array([100,  96,  70, 100,  87,  90])

In [179]:
grades

array([[100,  96,  70],
       [100,  87,  90]])

In [180]:
grades.T

array([[100, 100],
       [ 96,  87],
       [ 70,  90]])

In [181]:
grades

array([[100,  96,  70],
       [100,  87,  90]])

In [182]:
grades2 = ([[94, 77, 90], [100, 81, 82]])

In [183]:
np.hstack((grades, grades2))

array([[100,  96,  70,  94,  77,  90],
       [100,  87,  90, 100,  81,  82]])

In [184]:
np.vstack((grades, grades2))

array([[100,  96,  70],
       [100,  87,  90],
       [ 94,  77,  90],
       [100,  81,  82]])

#### Self Check 7.13

In [186]:
import numpy as np

In [187]:
a = np.arange(1, 7).reshape(2, 3)

In [188]:
a = np.hstack((a, a))

In [189]:
a = np.vstack((a, a))

In [190]:
a

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6],
       [1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])